### ISSUE TITLE
Imported to Yomitan's Dictionary, Not Working

### ISSUE THREAD

**Issue by EvilPuinda** [stephenmk/yomitan-jlpt-vocab#4]
I imported the JLPT.zip file to Yomitan's dictionary.  When I search for Japanese words like 読める、食べる, it says no results found. 
![Dictionary settings](https://github.com/user-attachments/assets/f1bef659-a001-4fd7-867c-cc19d073deb7)

![Search Results](https://github.com/user-attachments/assets/70054806-68b3-4ec6-bdf7-b8006b3e1b92)

**Comment by stephenmk** [comment]
That's just how yomitan works. You must have a dictionary which contains term data (such as Jitendex) enabled in order to see tags from dictionaries with term metadata.

**Comment by EvilPuinda** [comment]
Thanks. I did enable Jitendex but when looking up the Japanese words 読める、食べる it only shows the meaning of the kanji "eat" and "read" and doesn't show the meaning "to eat" or "to read."

**Comment by stephenmk** [comment]
> it only shows the meaning of the kanji "eat" and "read" and doesn't show the meaning "to eat" or "to read."

It sounds like you're only seeing the entries from the "KANJIDIC" dictionary that you have installed. It's possible that an error occurred when you imported Jitendex which resulted in many missing entries. All I can say is that you could try deleting it and attempt to import it again. There are no problems with the dictionary files that I have published, so there's not much I can do to help. You may want to ask the [yomitan community](https://yomitan.wiki/) for assistance.
